### ISSUE TITLE
How to change the Save Path and Filename of the Favicons?

### ISSUE THREAD

**Issue by raitman005** [gaffling/PHP-Grab-Favicon#2]
Hello, What if i want to use the file location dir of the favicon instead of the domain name on saving the file, where do i change it in the file?
domain/favicon href value.png

**Comment by gaffling** [comment]
Hello raitman005,

thanks for getting in touch. The filename is generated in line 119:

`$filePath = preg_replace('#\/\/#', '/', $directory.'/'.$domain.'.png');`

there you can change it in what you like, but if you will save the favicon image in a subfolder don't forget to mkdir() it before you save ;-)

Best Regards

**Comment by raitman005** [comment]
Is there a reason why i receive 504 gateway timeout error whenever i tried to fetch 50 favicon icons?

**Comment by gaffling** [comment]
it would be the reason that you PHP have a defined max. script runtime that is shorter than the script need to run do get the 50 icons, so you can try this at the beginning of the script:

`set_time_limit(0);  // NO TIME LIMIT`

**Comment by LeeThompson** [comment]
With #5 I'm implementing a switch to allow setting the local path (--path or -p).

**Comment by LeeThompson** [comment]
With the current version you can set the path on the command line with `--path=PATH` (Can be absolute or relative).    In web-mode there isn't an easy method (yet), you'll need to edit the PHP and change the `define('DEFAULT_LOCAL_PATH', "./");` to the path you want to use.

If you don't want to change it there, change:
`setConfiguration("files","local_path",DEFAULT_LOCAL_PATH);`
to
`setConfiguration("files","local_path","your path");`

**Comment by gaffling** [comment]
@LeeThompson You fixed this already, so I close this
