### ISSUE TITLE
Feature Ideas

### ISSUE THREAD

**Issue by LeeThompson** [gaffling/PHP-Grab-Favicon#5]
1. I will likely add this for myself locally but others may find it useful too but to give it a list of domains via stdin or a text file would be great.
2. Should probably accept some other command line options too, such as save/don't save, save path, debug messages, etc.

**Comment by gaffling** [comment]
Like your ideas, if you do so it would be very kind if you make also a `Pull Request` and get the fame 😄

**Comment by LeeThompson** [comment]
I've made a fork and  I'm working on stuff:
Most of this stuff isn't fully tested yet.

Command Line Switches:
- [x] --list (or -l) can be a text file with a list or URLs or a , ; or space delimited list.
- [x] --path (or -p), local save path
- [x] --store;  store local files
- [x] --nostore; do not store local files
- [x] --tryhomepage; try homepage first
- [x] --onlyuseapis; only use apis
- [x] --debug; enable debug mode
- [ ] --stdin; pass the list of URLs via STDIN 
- [ ] --help (or -?)

Other Features:
- [x] Detects image format and saves the local file accordingly
- [ ] "Console Mode" shows regular text instead of HTML 

Other Items:
- [ ] Check local file, needs to check multiple potential extensions.
- [ ] Want to add an overwrite/nooverwrite options for saving local files

**Comment by LeeThompson** [comment]
Submitted as a PR
NOTE: Needs testing.

Resubmitted the PR with some additional fixes and features.
